##########################################################################
# If not stated otherwise in this file or this component's Licenses.txt
# file the following copyright and licenses apply:
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################
'''
<?xml version="1.0" encoding="UTF-8"?><xml>
  <id/>
  <version>5</version>
  <name>TS_PAM_CheckSSHRemoteAccessStatus</name>
  <primitive_test_id/>
  <primitive_test_name>pam_GetParameterValues</primitive_test_name>
  <primitive_test_version>1</primitive_test_version>
  <status>FREE</status>
  <synopsis>This testcase check if remote access via ssh is enabled or not</synopsis>
  <groups_id/>
  <execution_time>5</execution_time>
  <long_duration>false</long_duration>
  <remarks/>
  <skip>false</skip>
  <box_types>
    <box_type>RPI</box_type>
    <box_type>Emulator</box_type>
    <box_type>Broadband</box_type>
  </box_types>
  <rdk_versions>
    <rdk_version>RDKB</rdk_version>
  </rdk_versions>
  <test_cases>
    <test_case_id>TC_PAM_95</test_case_id>
    <test_objective>To check if remote access via ssh is enabled or not</test_objective>
    <test_type>Positive</test_type>
    <test_setup>Emulator,XB3</test_setup>
    <pre_requisite>1.Ccsp Components in DUT should be in a running state that includes component under test Cable Modem
2.TDK Agent should be in running state or invoke it through StartTdk.sh script</pre_requisite>
    <api_or_interface_used>None</api_or_interface_used>
    <input_parameters>Json Interface:
API Name
pam_GetParameterValues

Input:
ParamName -
Device.UserInterface.X_CISCO_COM_RemoteAccess.SSHEnable</input_parameters>
    <automation_approch>1.Function which needs to be tested will be configured in Test Manager GUI.
2.Python Script will be generated by Test Manager with provided arguments in configure page.
3.TM will load the PAM library via Test agent
4.From python script, invoke pam_GetParameterValues() stub function to get the details of remote access via ssh .
5.pam stub function will call the ssp_getParameterValue() function of tdk component.
6.Responses from the pam stub function will be logged in Agent Console log.
7.pam stub will validate the actual result with the expected result and send the result status to Test Manager.
8.Test Manager will publish the result in GUI as PASS/FAILURE based on the response from pam stub.</automation_approch>
    <except_output>CheckPoint 1:
 The output  should be logged in the Agent console/Component log

CheckPoint 2:
Stub function result should be success and should see corresponding log in the agent console log

CheckPoint 3:
TestManager GUI will publish the result as PASS in Execution/Console page of Test Manager</except_output>
    <priority>High</priority>
    <test_stub_interface>None</test_stub_interface>
    <test_script>TS_PAM_CheckSSHRemoteAccessStatus</test_script>
    <skipped>No</skipped>
    <release_version/>
    <remarks/>
  </test_cases>
  <script_tags/>
</xml>

'''
#import statement
import tdklib;

#Test component to be tested
obj = tdklib.TDKScriptingLibrary("pam","RDKB");

#IP and Port of box, No need to change,
#This will be replaced with correspoing Box Ip and port while executing script
ip = <ipaddress>
port = <port>
obj.configureTestCase(ip,port,'TS_PAM_CheckSSHRemoteAccessStatus');

#Get the result of connection with test component and STB
loadmodulestatus =obj.getLoadModuleResult();
print "[LIB LOAD STATUS]  :  %s" %loadmodulestatus ;

if "SUCCESS" in loadmodulestatus.upper():
    #Set the result status of execution
    obj.setLoadModuleStatus("SUCCESS");
    tdkTestObj = obj.createTestStep('pam_GetParameterValues');
    tdkTestObj.addParameter("ParamName","Device.UserInterface.X_CISCO_COM_RemoteAccess.SSHEnable");
    expectedresult="SUCCESS";

    #Execute the test case in STB
    tdkTestObj.executeTestCase(expectedresult);
    actualresult = tdkTestObj.getResult();
    details = tdkTestObj.getResultDetails();
    if expectedresult in actualresult:
        #Set the result status of execution
        tdkTestObj.setResultStatus("SUCCESS");
        #Get the result of execution
        print "STEP 1: Get the boolean value whether remote access via ssh is enabled or not";
        print "EXPECTED RESULT 1 : Should get the boolean value whether remote access via ssh is enabled or not";
        print "ACTUAL RESULT 1: Successfully get the boolean value, %s" %details;
        print "[TEST EXECUTION RESULT] :%s" %actualresult;
	if "true" in details:
	    org = "true";
	else:
	    org = "false";
	print "default value is %s " %org;
        tdkTestObj = obj.createTestStep('pam_SetParameterValues');
        tdkTestObj.addParameter("ParamName","Device.UserInterface.X_CISCO_COM_RemoteAccess.SSHEnable");
        tdkTestObj.addParameter("Type","boolean");
	tdkTestObj.addParameter("ParamValue","true");
	tdkTestObj.executeTestCase(expectedresult);
	actualresult = tdkTestObj.getResult();
	details = tdkTestObj.getResultDetails();
	if expectedresult in actualresult:
            tdkTestObj.setResultStatus("SUCCESS");
            print "STEP 2: Set the boolean value to true ";
            print "EXPECTED RESLUT 2: Should set the boolean value to true ";
            print "ACTUAL RESULT 2: Successfully set the boolean value, %s" %details;
            print "[TEST EXECUTION RESULT] :%s" %actualresult;
	    tdkTestObj = obj.createTestStep('pam_GetParameterValues');
	    tdkTestObj.addParameter("ParamName","Device.UserInterface.X_CISCO_COM_RemoteAccess.SSHEnable");
	    expectedresult="SUCCESS";

	    #Execute the test case in STB
	    tdkTestObj.executeTestCase(expectedresult);
	    actualresult = tdkTestObj.getResult();
	    details = tdkTestObj.getResultDetails();
	    if expectedresult in actualresult:
		if "true" in details:
	            #Set the result status of execution
        	    tdkTestObj.setResultStatus("SUCCESS");
	            print "TEST STEP 3: Check if remote access via ssh is enabled or not";
        	    print "EXPECTED RESULT 3: Should get the status of remote access via ssh as true";
	            print "ACTUAL RESULT 3: The status of remote access via ssh :%s" %details;
        	    #Get the result of execution
	            print "[TEST EXECUTION RESULT] : SUCCESS"
		    #setting default value
		    tdkTestObj = obj.createTestStep('pam_SetParameterValues');
		    tdkTestObj.addParameter("ParamName","Device.UserInterface.X_CISCO_COM_RemoteAccess.SSHEnable");
	            tdkTestObj.addParameter("Type","boolean");
 	            tdkTestObj.addParameter("ParamValue",org);
		    tdkTestObj.executeTestCase(expectedresult);
		    actualresult = tdkTestObj.getResult();
		    details = tdkTestObj.getResultDetails();
	            if expectedresult in actualresult:
	                tdkTestObj.setResultStatus("SUCCESS");
            		print "STEP 4: Set the boolean value to default value ";
	                print "EXPECTED RESLUT 4: Should set the boolean value to default value ";
            		print "ACTUAL RESULT 4: Successfully set the boolean value, %s" %details;
	                print "[TEST EXECUTION RESULT] :%s" %actualresult;
		    else:
			tdkTestObj.setResultStatus("SUCCESS");
                        print "STEP 3: Set the boolean value to default value";
                        print "EXPECTED RESLUT 3: Should set the boolean value to default value ";
                        print "ACTUAL RESULT 3: Successfully set the boolean value, %s" %details;
                        print "[TEST EXECUTION RESULT] :%s" %actualresult;
		else:
		    #Set the result status of execution
		    tdkTestObj.setResultStatus("FAILURE");
		    print "TEST STEP 2: Check if remote access via ssh is enabled or not";
		    print "EXPECTED RESULT 2: Should get the status of remote access via ssh as true";
		    print "ACTUAL RESULT 2: The status of remote access via ssh :%s" %details;
		    #Get the result of execution
		    print "[TEST EXECUTION RESULT] : FAILURE"
            else:
	        tdkTestObj.setResultStatus("FAILURE");
	        print "TEST STEP 2: Check if remote access via ssh is enabled or not";
        	print "EXPECTED RESULT 2: Should get the status of remote access via ssh";
	        print "ACTUAL RESULT 2: Failure in getting the status of remote access via ssh. Details : %s" %details;
        	print "[TEST EXECUTION RESULT] : FAILURE";
        else:
	    tdkTestObj.setResultStatus("FAILURE");
	    print "STEP 1: Set the boolean value to true ";
            print "EXPECTED RESLUT 1: Should set the boolean value to true ";
            print "ACTUAL RESULT 1: Failed to set the boolean value, %s" %details;
            print "[TEST EXECUTION RESULT] :%s" %actualresult;
    else:
        tdkTestObj.setResultStatus("FAILURE");
        print "STEP 1: Get the boolean value whether remote access via ssh is enabled or not";
        print "EXPECTED RESULT : Should get the boolean value whether remote access via ssh is enabled or not";
        print "ACTUAL RESULT: Successfully get the boolean value, %s" %details;
        print "[TEST EXECUTION RESULT] :%s" %actualresult;

    obj.unloadModule("pam");

else:
        print "Failed to load pam module";
        obj.setLoadModuleStatus("FAILURE");
        print "Module loading failed";
