#########################################################################
# If not stated otherwise in this file or this component's Licenses.txt
# file the following copyright and licenses apply:
#
# Copyright 2019 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################
'''
<?xml version="1.0" encoding="UTF-8"?><xml>
  <id/>
  <version>1</version>
  <name>TS_SANITY_CheckMocaStatus_OnBridgeMode</name>
  <primitive_test_id/>
  <primitive_test_name>ExecuteCmd</primitive_test_name>
  <primitive_test_version>1</primitive_test_version>
  <status>FREE</status>
  <synopsis>Check if the moca status is disabled  in bridge mode and enabled again in router mode</synopsis>
  <groups_id/>
  <execution_time>15</execution_time>
  <long_duration>false</long_duration>
  <advanced_script>false</advanced_script>
  <remarks/>
  <skip>false</skip>
  <box_types>
    <box_type>Broadband</box_type>
  </box_types>
  <rdk_versions>
    <rdk_version>RDKB</rdk_version>
  </rdk_versions>
  <test_cases>
    <test_case_id>TC_SYSUTIL_26</test_case_id>
    <test_objective>Check if the moca status is disabled in bridge mode and getting enabled again in router mode</test_objective>
    <test_type>Positive</test_type>
    <test_setup>Broadband</test_setup>
    <pre_requisite>TDK Agent should be in running state or invoke it through StartTdk.sh script</pre_requisite>
    <api_or_interface_used>None</api_or_interface_used>
    <input_parameters>None</input_parameters>
    <automation_approch>1.Function which needs to be tested will be configured in Test Manager GUI.
2.Python Script will be generated by Test Manager with provided arguments in configure page.
3.TM will load the sysutil library via Test agent
4.Get the status of moca
5.Get the lan mode
6.If lan mode is bridge mode, check whether moca status is disabled
7.If lan mode is not bridge mode,check whether moca status is enabled/not. If not enabled set it to true and set lan mode to bridge mode. get the moca status,it should be disabled. set the lanmode to router and get the moca status, the status should be true.
8. revert back the values to initial
9.Responses from the sysutil stub function will be logged in Agent Console log.
10.Test Manager will publish the result in GUI as PASS/FAILURE</automation_approch>
    <except_output>the moca status is disabled in bridge mode and getting enabled again in router mode</except_output>
    <priority>High</priority>
    <test_stub_interface>sysutil</test_stub_interface>
    <test_script>TS_SANITY_CheckMocaStatus_OnBridgeMode</test_script>
    <skipped>No</skipped>
    <release_version>M67</release_version>
    <remarks/>
  </test_cases>
</xml>

'''
# use tdklib library,which provides a wrapper for tdk testcase script
import tdklib;
from tdkbVariables import *;
from time import sleep;

#Test component to be tested
obj = tdklib.TDKScriptingLibrary("tdkbtr181","RDKB");
#IP and Port of box, No need to change,
#This will be replaced with correspoing Box Ip and port while executing script
ip = <ipaddress>
port = <port>
obj.configureTestCase(ip,port,'TS_SANITY_CheckMocaStatus_OnBridgeMode');
#Get the result of connection with test component and DUT
loadmodulestatus =obj.getLoadModuleResult();
if "SUCCESS" in loadmodulestatus.upper():
    obj.setLoadModuleStatus("SUCCESS");
    tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Get');
    tdkTestObj.addParameter("ParamName","Device.MoCA.Interface.1.Enable");
    expectedresult="SUCCESS";
    #Execute the test case in DUT
    tdkTestObj.executeTestCase(expectedresult);
    actualresult = tdkTestObj.getResult();
    details = tdkTestObj.getResultDetails();
    mocaInitial = details;

    if expectedresult in actualresult:
        #Set the result status of execution
        tdkTestObj.setResultStatus("SUCCESS");
        print "TEST STEP 1: Get the enable status of Moca";
        print "EXPECTED RESULT 1: Should get the enable status of Moca";
        print "ACTUAL RESULT 1: Moca Enable status is %s" %mocaInitial;
        #Get the result of execution
        print "[TEST EXECUTION RESULT] : SUCCESS";

        tdkTestObj.addParameter("ParamName","Device.X_CISCO_COM_DeviceControl.LanManagementEntry.1.LanMode");
        #Execute the test case in DUT
        tdkTestObj.executeTestCase(expectedresult);
        actualresult = tdkTestObj.getResult();
        lanmodeInitial = tdkTestObj.getResultDetails();

        if expectedresult in actualresult:
           #Set the result status of execution
           tdkTestObj.setResultStatus("SUCCESS");
           print "TEST STEP 2: Get the lanmode";
           print "EXPECTED RESULT 2: Should get the lanmode";
           print "ACTUAL RESULT 2: Lanmode is :",lanmodeInitial;
           #Get the result of execution
           print "[TEST EXECUTION RESULT] : SUCCESS";

           if lanmodeInitial == "bridge-static":
              print "The Device is in bridge static mode"
              tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Get');
    	      tdkTestObj.addParameter("ParamName","Device.MoCA.Interface.1.Enable");
    	      #Execute the test case in DUT
    	      tdkTestObj.executeTestCase(expectedresult);
    	      actualresult = tdkTestObj.getResult();
    	      mocaStatus_new = tdkTestObj.getResultDetails();
              if expectedresult in actualresult and mocaStatus_new == "false":
                 tdkTestObj.setResultStatus("SUCCESS");
                 print "TEST STEP 4: Get the enable status of Moca";
                 print "EXPECTED RESULT 4: Should get the enable status of Moca false in bridge-static mode";
                 print "ACTUAL RESULT 4: Moca Enable status is %s" %mocaStatus_new;
                 #Get the result of execution
                 print "[TEST EXECUTION RESULT] : SUCCESS";
              else:
                  #Set the result status of execution
                  tdkTestObj.setResultStatus("FAILURE");
                  print "TEST STEP 4: Get the enable status of Moca";
                  print "EXPECTED RESULT 4: Should get the enable status of Moca disabled in bridge-static mode";
                  print "ACTUAL RESULT 4: Moca Enable status is %s" %mocaStatus_new
                  #Get the result of execution
                  print "[TEST EXECUTION RESULT] : FAILURE";
           else:
               print "The Device is in router mode"
               print "Checking if the moca status is true else set it to true"
               flag = 1
               if mocaInitial == "false" :
                  #setting moca status to true
                  tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Set');
                  tdkTestObj.addParameter("ParamName","Device.MoCA.Interface.1.Enable");
                  tdkTestObj.addParameter("ParamValue","true");
                  tdkTestObj.addParameter("Type","boolean");

                  #Execute the test case in DUT
                  tdkTestObj.executeTestCase(expectedresult);
                  actualresult = tdkTestObj.getResult();
                  details = tdkTestObj.getResultDetails();

                  if expectedresult in actualresult:
                     flag = 0
                     #Set the result status of execution
                     tdkTestObj.setResultStatus("SUCCESS");
                     print "TEST STEP 3:  Setting the moca status to true";
                     print "EXPECTED RESULT 3: Should set the moca status to true";
                     print "ACTUAL RESULT 3: %s" %details;
                     #Get the result of execution
                     print "[TEST EXECUTION RESULT] : SUCCESS";
               else:
                   flag = 0
                   print "The Moca status is already set to true"

               if flag == 0:
                  #setting lan-mode to bridge static

                  tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Set');
                  tdkTestObj.addParameter("ParamName","Device.X_CISCO_COM_DeviceControl.LanManagementEntry.1.LanMode");
                  tdkTestObj.addParameter("ParamValue","bridge-static");
                  tdkTestObj.addParameter("Type","string");


                  #Execute the test case in DUT
                  tdkTestObj.executeTestCase(expectedresult);
                  actualresult = tdkTestObj.getResult();
                  details = tdkTestObj.getResultDetails();

                  if expectedresult in actualresult:
                     #Set the result status of execution
                     tdkTestObj.setResultStatus("SUCCESS");
                     print "TEST STEP 4:  Setting the  lanmode to bridge static";
                     print "EXPECTED RESULT 4: Should set the lanmode to bridge-static";
                     print "ACTUAL RESULT 4: %s" %details;
                     #Get the result of execution
                     print "[TEST EXECUTION RESULT] : SUCCESS";
                     
                     obj.setLoadModuleStatus("SUCCESS");
                     tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Get');
                     tdkTestObj.addParameter("ParamName","Device.MoCA.Interface.1.Enable");
                     expectedresult="SUCCESS";
                     # adding sleep  to reflect status of Moca after changing lan mode
                     sleep(20);
                     #Execute the test case in DUT
                     tdkTestObj.executeTestCase(expectedresult);
                     actualresult = tdkTestObj.getResult();
                     mocaStatus_new  = tdkTestObj.getResultDetails();


                     if expectedresult in actualresult and mocaStatus_new == "false":
                        tdkTestObj.setResultStatus("SUCCESS");
                        print "TEST STEP 4: Get the enable status of Moca";
                        print "EXPECTED RESULT 4: Should get the enable status of Moca false in bridge-static mode";
                        print "ACTUAL RESULT 4: Moca Enable status is %s" %mocaStatus_new;
                        #Get the result of execution
                        print "[TEST EXECUTION RESULT] : SUCCESS";

                        #setting lan-mode to router to verify if the moca status is enabled

                        tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Set');
                        tdkTestObj.addParameter("ParamName","Device.X_CISCO_COM_DeviceControl.LanManagementEntry.1.LanMode");
                        tdkTestObj.addParameter("ParamValue","router");
                        tdkTestObj.addParameter("Type","string");


                        #Execute the test case in DUT
                        tdkTestObj.executeTestCase(expectedresult);
                        actualresult = tdkTestObj.getResult();
                        details = tdkTestObj.getResultDetails();

                        if expectedresult in actualresult:
                           #Set the result status of execution
                           tdkTestObj.setResultStatus("SUCCESS");
                           print "TEST STEP 5:  Setting the  lanmode to router";
                           print "EXPECTED RESULT 5: Should set the lanmode to router";
                           print "ACTUAL RESULT 5: %s" %details;
                           #Get the result of execution
                           print "[TEST EXECUTION RESULT] : SUCCESS";
                          
                           tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Get');
                           tdkTestObj.addParameter("ParamName","Device.MoCA.Interface.1.Enable");
                           # adding sleep  to reflect status of Moca after changing lan mode
                           sleep(20);
                           #Execute the test case in DUT
                           tdkTestObj.executeTestCase(expectedresult);
                           actualresult = tdkTestObj.getResult();
                           mocaStatus_new = tdkTestObj.getResultDetails();

                           if expectedresult in actualresult and mocaStatus_new == "true":
                              tdkTestObj.setResultStatus("SUCCESS");
                              print "TEST STEP 6: Get the enable status of Moca";
                              print "EXPECTED RESULT 6: Moca status should be enabled in router mode ";
        	              print "ACTUAL RESULT 6: Moca Enable status is %s" %mocaStatus_new;
                              #Get the result of execution
                              print "[TEST EXECUTION RESULT] : SUCCESS";
                           else:
                               #Set the result status of execution
                               tdkTestObj.setResultStatus("FAILURE");
                               print "TEST STEP 6: Get the enable status of Moca";
                               print "EXPECTED RESULT 6: Moca status should be enabled in router mode ";
                               print "ACTUAL RESULT 6: Moca Enable status is %s" %mocaStatus_new
                               #Get the result of execution
                               print "[TEST EXECUTION RESULT] : FAILURE";
                        else:
                            #Set the result status of execution
                            tdkTestObj.setResultStatus("FAILURE");
                            print "TEST STEP 5:  Setting the  lanmode to router";
                            print "EXPECTED RESULT 5: Should set the lanmode to router";
                            print "ACTUAL RESULT 5: %s" %details;
                            #Get the result of execution
                            print "[TEST EXECUTION RESULT] : FAILURE";
                     else:
                        #Set the result status of execution
                        tdkTestObj.setResultStatus("FAILURE");
                        print "TEST STEP 4: Get the enable status of Moca";
                        print "EXPECTED RESULT 4: Should get the enable status of Moca disabled in bridge-static mode";
                        print "ACTUAL RESULT 4: Moca Enable status is %s" %mocaStatus_new
                        #Get the result of execution
                        print "[TEST EXECUTION RESULT] : FAILURE";

                     #Set lan mode to previous value
                     tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Set');
                     tdkTestObj.addParameter("ParamName","Device.X_CISCO_COM_DeviceControl.LanManagementEntry.1.LanMode");
                     tdkTestObj.addParameter("ParamValue",lanmodeInitial);
                     tdkTestObj.addParameter("Type","string");

                     #Execute the test case in DUT
                     tdkTestObj.executeTestCase(expectedresult);
                     actualresult = tdkTestObj.getResult();
                     details = tdkTestObj.getResultDetails();

                     if expectedresult in actualresult:
                        #Set the result status of execution
                        tdkTestObj.setResultStatus("SUCCESS");
                        print "TEST STEP 5: Set the lanmode to previous value";
                        print "EXPECTED RESULT 5: Should set the lanmode to previous value";
                        print "ACTUAL RESULT 5: %s" %details;
                        #Get the result of execution
                        print "[TEST EXECUTION RESULT] : SUCCESS";
                     else:
                         #Set the result status of execution
                         tdkTestObj.setResultStatus("FAILURE");
                         print "TEST STEP 5: Set the lanmode to previous value";
                         print "EXPECTED RESULT 5: Should set the lanmode to previous value";
                         print "ACTUAL RESULT 5: %s" %details;
                         #Get the result of execution
                         print "[TEST EXECUTION RESULT] : FAILURE";




                     #Set moca Enable status  to previous value
                     tdkTestObj = obj.createTestStep('TDKB_TR181Stub_Set');
                     tdkTestObj.addParameter("ParamName","Device.MoCA.Interface.1.Enable");
                     tdkTestObj.addParameter("ParamValue",mocaInitial);
                     tdkTestObj.addParameter("Type","boolean");

                     #Execute the test case in DUT
                     tdkTestObj.executeTestCase(expectedresult);
                     actualresult = tdkTestObj.getResult();
                     details = tdkTestObj.getResultDetails();

                     if expectedresult in actualresult:
                        #Set the result status of execution
                        tdkTestObj.setResultStatus("SUCCESS");
                        print "TEST STEP 5: Set the moca enable state to previous value";
                        print "EXPECTED RESULT 5: Should set the moca enable state to previous value";
                        print "ACTUAL RESULT 5: %s" %details;
                        #Get the result of execution
                        print "[TEST EXECUTION RESULT] : SUCCESS";
                     else:
                         #Set the result status of execution
                         tdkTestObj.setResultStatus("FAILURE");
                         print "TEST STEP 5: Set the moca enable state  to previous value";
                         print "EXPECTED RESULT 5: Should set the moca enable state  to previous value";
                         print "ACTUAL RESULT 5: %s" %details;
                         #Get the result of execution
                         print "[TEST EXECUTION RESULT] : FAILURE";
                  else:
                      #Set the result status of execution
                      tdkTestObj.setResultStatus("FAILURE");
                      print "TEST STEP 4:  Setting the  lanmode to bridge static";
                      print "EXPECTED RESULT 4: Should set the lanmode to bridge-static";
                      print "ACTUAL RESULT 4: %s" %details;
                      #Get the result of execution
                      print "[TEST EXECUTION RESULT] :FAILURE";
               else:
                   #Set the result status of execution
                   tdkTestObj.setResultStatus("FAILURE");
                   print "TEST STEP 1: Set the enable status of Moca to true";
                   print "EXPECTED RESULT 1: Should set the enable status of Moca to true";
                   print "ACTUAL RESULT 1: Moca Enable status is %s" %mocaStatus;
                   #Get the result of execution
                   print "[TEST EXECUTION RESULT] : FAILURE";

        else:

	    #Set the result status of execution
            tdkTestObj.setResultStatus("FAILURE");
            print "TEST STEP 2: Get the lanmode";
            print "EXPECTED RESULT 2: Should get the lanmode";
            print "ACTUAL RESULT 2: Lanmode is %s" %lanmodeInitial;
            #Get the result of execution
            print "[TEST EXECUTION RESULT] : FAILURE";
    else:
	#Set the result status of execution
        tdkTestObj.setResultStatus("FAILURE");
        print "TEST STEP 1: Get the enable status of Moca";
        print "EXPECTED RESULT 1: Should get the enable status of Moca";
        print "ACTUAL RESULT 1: Moca Enable status is %s" %mocaStatus;
        #Get the result of execution
        print "[TEST EXECUTION RESULT] : FAILURE";
    obj.unloadModule("tdkbtr181");
else:
        print "Failed to load sysutil module";
        obj.setLoadModuleStatus("FAILURE");
        print "Module loading failed"
